* Thesis Statement Notes
** Goals
   - Exploring simulation of plastic surgery flap operations on isolated regions and the scalp
   - Exploring potential performance opportunities stemming from lattice based deformers
   - Understanding issues and challenges with designing and deploying simulation tools in practical settings
** Deliverables / Results
   - A software artifact: Authoring tool for designing educational representations of surgical operations
     - High performance elastic simulation
     - Support for topological cutting
     - Support for advanced, nonlinear material models
     - Support for rigid body collisions
     - Distributed deployment model with multiple simultaneous web front-ends
   - Approval / excitement of domain expert
   - Several peer-reviewed papers covering core technologies
     - Advanced material models with lattice deformers (Patterson 2012)
     - Supporting high performance surgical simulation (Mitchell 2015)
     - Non-manifold levelsets for high performance self collisions (Mitchell 2015)
     - Optimized schur-complement block solvers for lattice deformers (Mitchell 2016)  
   - Feasibility demo demonstrating core software functionality and deployment design
** Revision notes (March 16 2017)
   - dimension (geometry?) geometry and space, materiality
   - purpose - enumerate concrete, but disjoint examples
   - challanges come after specific example (they make more sense)
      - Cater to needs, talk about medical simulation, talk about concrete and abstract, and how the abstract connects with specific instance
      - utility
	- observing behaviors recognising patterns
	  - if these are useful, does our reconstruction match these real properties
	  - visual - identitgy landmarks
        - need to comprise, where and when?
          - utility, what is important to us
        - not all comprises are equal
** Revision notes (March 28 2017)
   How does what I've done support generality over what a system specifically designed for surgery

   Blocking = preserve applicability for other systems.

   Problem dissection

      largely didatic, peel away layers, arrive at numerical challenges

      deforming solid that reacts to internal mechanics and external stimuli

         state representation / continous? / discrete?
            pertantant mechanical properties: position, velocity? 

	    dynamic / quasistatic / static
            Time as a first class citizen
            slowing down external stimuli - playback at high speed.
            quasi-static - time-independent

        reference configugration
          alternatives ? particles, mesh, 
          vs. texture mapping, texture coordinates
          how to choose? does not need to map to zero energy configuration

        user interactions
         topology actions
         position constraints
         force constraints
         contact constraints

       discretization
          why? no anaylitcal description
          how to move from continuous to discrete
          what is our base discrete element? Cube, tet, something more exotic?
          Is material exact vs embededed (conforming)

** Revision notes (April 25 2017)

   (3.1) Second paragraph - purpose

   Last paragraph - perhaps state less alternatives, focus more on our model.

   (3.2) deformation defination 
        continous collection of material points with some glue between them

        reference configuration serves as a name space for labeling material points
        also used as shape, if material is placed in, which exhbits no mechanical response

   
